import { ComponentRegistry } from './registry';
import { ComponentMetadata } from './types';

export const INITIAL_COMPONENTS: ComponentMetadata[] = [
  // 1. Passive: Resistor
  {
    id: 'Resistor',
    name: 'Resistor',
    tvcs: {
      categoryPath: ['Passive'],
      manufacturer: 'Generic',
      series: '',
      family: 'Passive',
      variant: '',
      tags: [],
      package: 'Generic',
      footprint: 'Generic',
      physicalDimensions: { widthMm: 0, lengthMm: 0, heightMm: 0 },
      electrical: { operatingVoltageMin: 0, operatingVoltageMax: 0, logicVoltage: 0 },
      interfaces: [],
      protocols: []
    },
    aliases: ['res', 'r'],
    keywords: ['resistor', 'passive', 'component'],
    description: 'Standard axial leaded film resistor',
    visual: {
      symbol: 'resistor',
      width: 80,
      height: 40,
    },
    geometry: {
      body: 'rect',
      pins: [
        { id: '1', x: 0, y: 20 },
        { id: '2', x: 80, y: 20 },
      ],
      boundingBox: { x: 0, y: 0, width: 80, height: 40 },
    },
    electrical: {
      pins: [
        {
          id: '1',
          name: '1',
          aliases: ['p1', 'terminal_1'],
          electricalType: 'passive',
          direction: 'passive',
        },
        {
          id: '2',
          name: '2',
          aliases: ['p2', 'terminal_2'],
          electricalType: 'passive',
          direction: 'passive',
        },
      ],
    },
    knowledge: {
      notes: ['Non-polar component'],
      warnings: ['Do not exceed power rating'],
      applications: ['Current limiting', 'Voltage divider'],
      tags: ['passive', 'resistor'],
    },
  },
  // 2. Passive: Capacitor
  {
    id: 'Capacitor',
    name: 'Capacitor',
    tvcs: {
      categoryPath: ['Passive'],
      manufacturer: 'Generic',
      series: '',
      family: 'Passive',
      variant: '',
      tags: [],
      package: 'Generic',
      footprint: 'Generic',
      physicalDimensions: { widthMm: 0, lengthMm: 0, heightMm: 0 },
      electrical: { operatingVoltageMin: 0, operatingVoltageMax: 0, logicVoltage: 0 },
      interfaces: [],
      protocols: []
    },
    aliases: ['cap', 'c'],
    keywords: ['capacitor', 'passive', 'filter'],
    description: 'Ceramic disc capacitor',
    visual: {
      symbol: 'capacitor',
      width: 80,
      height: 40,
    },
    geometry: {
      body: 'circle',
      pins: [
        { id: '1', x: 0, y: 20 },
        { id: '2', x: 80, y: 20 },
      ],
      boundingBox: { x: 0, y: 0, width: 80, height: 40 },
    },
    electrical: {
      pins: [
        {
          id: '1',
          name: '1',
          aliases: ['p1'],
          electricalType: 'passive',
          direction: 'passive',
        },
        {
          id: '2',
          name: '2',
          aliases: ['p2'],
          electricalType: 'passive',
          direction: 'passive',
        },
      ],
    },
    knowledge: {
      notes: ['Non-polar component'],
      warnings: ['Do not exceed voltage rating'],
      applications: ['Decoupling', 'Filtering'],
      tags: ['passive', 'capacitor'],
    },
  },
  // 3. Semiconductor: LED
  {
    id: 'LED',
    name: 'LED',
    tvcs: {
      categoryPath: ['Semiconductor'],
      manufacturer: 'Generic',
      series: '',
      family: 'Semiconductor',
      variant: '',
      tags: [],
      package: 'Generic',
      footprint: 'Generic',
      physicalDimensions: { widthMm: 0, lengthMm: 0, heightMm: 0 },
      electrical: { operatingVoltageMin: 0, operatingVoltageMax: 0, logicVoltage: 0 },
      interfaces: [],
      protocols: []
    },
    aliases: ['led', 'light_emitting_diode'],
    keywords: ['led', 'diode', 'light'],
    description: 'Standard 5mm T-1 3/4 LED',
    visual: {
      symbol: 'led',
      width: 80,
      height: 60,
    },
    geometry: {
      body: 'led_shape',
      pins: [
        { id: 'A', x: 0, y: 30 },
        { id: 'K', x: 80, y: 30 },
      ],
      boundingBox: { x: 0, y: 0, width: 80, height: 60 },
    },
    electrical: {
      pins: [
        {
          id: 'A',
          name: 'Anode',
          aliases: ['anode', 'a'],
          electricalType: 'anode',
          direction: 'passive',
        },
        {
          id: 'K',
          name: 'Cathode',
          aliases: ['cathode', 'k'],
          electricalType: 'cathode',
          direction: 'passive',
        },
      ],
    },
    knowledge: {
      notes: ['Polarized component'],
      warnings: ['Always use a current limiting resistor'],
      applications: ['Indicator', 'Illumination'],
      tags: ['semiconductor', 'led', 'diode'],
    },
  },
  // 4. Semiconductor: Diode
  {
    id: 'Diode',
    name: 'Diode',
    tvcs: {
      categoryPath: ['Semiconductor'],
      manufacturer: 'Generic',
      series: '',
      family: 'Semiconductor',
      variant: '',
      tags: [],
      package: 'Generic',
      footprint: 'Generic',
      physicalDimensions: { widthMm: 0, lengthMm: 0, heightMm: 0 },
      electrical: { operatingVoltageMin: 0, operatingVoltageMax: 0, logicVoltage: 0 },
      interfaces: [],
      protocols: []
    },
    aliases: ['diode', 'd'],
    keywords: ['diode', 'rectifier', 'semiconductor'],
    description: 'General purpose silicon rectifier diode',
    visual: {
      symbol: 'diode',
      width: 80,
      height: 40,
    },
    geometry: {
      body: 'diode_shape',
      pins: [
        { id: 'A', x: 0, y: 20 },
        { id: 'K', x: 80, y: 20 },
      ],
      boundingBox: { x: 0, y: 0, width: 80, height: 40 },
    },
    electrical: {
      pins: [
        {
          id: 'A',
          name: 'Anode',
          aliases: ['anode', 'a'],
          electricalType: 'anode',
          direction: 'passive',
        },
        {
          id: 'K',
          name: 'Cathode',
          aliases: ['cathode', 'k'],
          electricalType: 'cathode',
          direction: 'passive',
        },
      ],
    },
    knowledge: {
      notes: ['Polarized component'],
      warnings: ['Ensure correct polarity to prevent reverse breakdown'],
      applications: ['Rectification', 'Reverse polarity protection'],
      tags: ['semiconductor', 'diode'],
    },
  },
  // 5. Power: GND
  {
    id: 'GND',
    name: 'GND',
    tvcs: {
      categoryPath: ['Power'],
      manufacturer: 'Generic',
      series: '',
      family: 'Power',
      variant: '',
      tags: [],
      package: 'Generic',
      footprint: 'Generic',
      physicalDimensions: { widthMm: 0, lengthMm: 0, heightMm: 0 },
      electrical: { operatingVoltageMin: 0, operatingVoltageMax: 0, logicVoltage: 0 },
      interfaces: [],
      protocols: []
    },
    aliases: ['gnd', 'ground'],
    keywords: ['ground', 'gnd', 'power', '0v'],
    description: 'Ground reference node',
    visual: {
      symbol: 'gnd',
      width: 40,
      height: 40,
    },
    geometry: {
      body: 'gnd_shape',
      pins: [{ id: 'GND', x: 20, y: 0 }],
      boundingBox: { x: 0, y: 0, width: 40, height: 40 },
    },
    electrical: {
      pins: [
        {
          id: 'GND',
          name: 'GND',
          aliases: ['ground', '0v'],
          electricalType: 'power',
          direction: 'power_input',
        },
      ],
    },
    knowledge: {
      notes: ['Reference potential'],
      warnings: ['Ensure common ground across all schematic layers'],
      applications: ['Reference voltage', 'Current return path'],
      tags: ['power', 'ground', 'reference'],
    },
  },
  // 6. Power: VCC
  {
    id: 'VCC',
    name: 'VCC',
    tvcs: {
      categoryPath: ['Power'],
      manufacturer: 'Generic',
      series: '',
      family: 'Power',
      variant: '',
      tags: [],
      package: 'Generic',
      footprint: 'Generic',
      physicalDimensions: { widthMm: 0, lengthMm: 0, heightMm: 0 },
      electrical: { operatingVoltageMin: 0, operatingVoltageMax: 0, logicVoltage: 0 },
      interfaces: [],
      protocols: []
    },
    aliases: ['vcc', 'power_supply'],
    keywords: ['vcc', 'power', 'voltage', 'supply'],
    description: 'Positive power supply node',
    visual: {
      symbol: 'vcc',
      width: 40,
      height: 40,
    },
    geometry: {
      body: 'vcc_shape',
      pins: [{ id: 'VCC', x: 20, y: 40 }],
      boundingBox: { x: 0, y: 0, width: 40, height: 40 },
    },
    electrical: {
      pins: [
        {
          id: 'VCC',
          name: 'VCC',
          aliases: ['power_supply'],
          electricalType: 'power',
          direction: 'power_output',
        },
      ],
    },
    knowledge: {
      notes: ['Power rail potential'],
      warnings: ['Do not short to ground'],
      applications: ['Power delivery'],
      tags: ['power', 'vcc'],
    },
  },
  // 7. MCU: ESP32 DevKit
  {
    id: 'ESP32',
    name: 'ESP32 DevKit',
    tvcs: {
      categoryPath: ['MCU'],
      manufacturer: 'Generic',
      series: '',
      family: 'MCU',
      variant: '',
      tags: [],
      package: 'Generic',
      footprint: 'Generic',
      physicalDimensions: { widthMm: 0, lengthMm: 0, heightMm: 0 },
      electrical: { operatingVoltageMin: 0, operatingVoltageMax: 0, logicVoltage: 0 },
      interfaces: [],
      protocols: []
    },
    aliases: ['esp', 'esp32', 'mcu'],
    keywords: ['esp32', 'mcu', 'microcontroller', 'wifi', 'bluetooth', 'gpio'],
    description: 'ESP32-WROOM-32D Development Board',
    visual: {
      symbol: 'esp32',
      width: 120,
      height: 180,
    },
    geometry: {
      body: 'esp32_body',
      pins: [
        { id: '3V3', x: 0, y: 20 },
        { id: 'GND', x: 0, y: 40 },
        { id: 'GPIO2', x: 0, y: 60 },
        { id: 'GPIO4', x: 0, y: 80 },
        { id: 'GPIO5', x: 0, y: 100 },
        { id: 'GPIO18', x: 120, y: 20 },
        { id: 'GPIO19', x: 120, y: 40 },
        { id: 'GPIO21', x: 120, y: 60 },
        { id: 'GPIO22', x: 120, y: 80 },
        { id: 'GPIO23', x: 120, y: 90 }, // Match previous coordinate tests
      ],
      boundingBox: { x: 0, y: 0, width: 120, height: 180 },
    },
    electrical: {
      pins: [
        {
          id: '3V3',
          name: '3V3',
          aliases: ['3.3v'],
          electricalType: 'power',
          direction: 'power_output',
          voltageDomain: '3.3V',
        },
        {
          id: 'GND',
          name: 'GND',
          aliases: ['ground'],
          electricalType: 'power',
          direction: 'power_input',
        },
        {
          id: 'GPIO2',
          name: 'GPIO2',
          aliases: ['io2'],
          electricalType: 'digital',
          direction: 'bidirectional',
          voltageDomain: '3.3V',
        },
        {
          id: 'GPIO4',
          name: 'GPIO4',
          aliases: ['io4'],
          electricalType: 'digital',
          direction: 'bidirectional',
          voltageDomain: '3.3V',
        },
        {
          id: 'GPIO5',
          name: 'GPIO5',
          aliases: ['io5'],
          electricalType: 'digital',
          direction: 'bidirectional',
          voltageDomain: '3.3V',
        },
        {
          id: 'GPIO18',
          name: 'GPIO18',
          aliases: ['io18'],
          electricalType: 'digital',
          direction: 'bidirectional',
          voltageDomain: '3.3V',
        },
        {
          id: 'GPIO19',
          name: 'GPIO19',
          aliases: ['io19'],
          electricalType: 'digital',
          direction: 'bidirectional',
          voltageDomain: '3.3V',
        },
        {
          id: 'GPIO21',
          name: 'GPIO21',
          aliases: ['io21'],
          electricalType: 'digital',
          direction: 'bidirectional',
          voltageDomain: '3.3V',
        },
        {
          id: 'GPIO22',
          name: 'GPIO22',
          aliases: ['io22'],
          electricalType: 'digital',
          direction: 'bidirectional',
          voltageDomain: '3.3V',
        },
        {
          id: 'GPIO23',
          name: 'GPIO23',
          aliases: ['io23'],
          electricalType: 'digital',
          direction: 'bidirectional',
          voltageDomain: '3.3V',
        },
      ],
    },
    knowledge: {
      notes: ['Features built-in Wi-Fi and Bluetooth'],
      warnings: ['Maximum current draw on GPIO is 40mA', 'Do not connect 5V to 3.3V pin'],
      applications: ['IoT Projects', 'Home Automation'],
      tags: ['mcu', 'esp32', 'wifi', 'bluetooth'],
    },
  },
  // 8. Interface: Relay Module
  {
    id: 'Relay Module',
    name: 'Single Channel Relay Module',
    tvcs: {
      categoryPath: ['Interface'],
      manufacturer: 'Generic',
      series: '',
      family: 'Interface',
      variant: '',
      tags: [],
      package: 'Generic',
      footprint: 'Generic',
      physicalDimensions: { widthMm: 0, lengthMm: 0, heightMm: 0 },
      electrical: { operatingVoltageMin: 0, operatingVoltageMax: 0, logicVoltage: 0 },
      interfaces: [],
      protocols: []
    },
    aliases: ['relay', 'relay module'],
    keywords: ['relay', 'switch'],
    description: 'Single channel 5V relay module',
    visual: {
      symbol: 'relay',
      width: 100,
      height: 80,
    },
    geometry: {
      body: 'rect',
      pins: [
        { id: 'COM', x: 0, y: 25 },
        { id: 'NO', x: 0, y: 55 },
        { id: 'IN1', x: 100, y: 40 },
      ],
      boundingBox: { x: 0, y: 0, width: 100, height: 80 },
    },
    electrical: {
      pins: [
        {
          id: 'COM',
          name: 'COM',
          aliases: ['common'],
          electricalType: 'power',
          direction: 'passive',
        },
        {
          id: 'NO',
          name: 'NO',
          aliases: ['normally_open'],
          electricalType: 'power',
          direction: 'passive',
        },
        {
          id: 'IN1',
          name: 'IN1',
          aliases: ['input_1'],
          electricalType: 'digital',
          direction: 'input',
        },
      ],
    },
    knowledge: {
      notes: ['Switching capacity up to 10A'],
      warnings: ['Do not exceed voltage/current ratings'],
      applications: ['High voltage control'],
      tags: ['interface', 'relay'],
    },
  },
  // 9. Power: 12V Power Supply
  {
    id: '12V Power Supply',
    name: '12V DC Power Supply',
    tvcs: {
      categoryPath: ['Power'],
      manufacturer: 'Generic',
      series: '',
      family: 'Power',
      variant: '',
      tags: [],
      package: 'Generic',
      footprint: 'Generic',
      physicalDimensions: { widthMm: 0, lengthMm: 0, heightMm: 0 },
      electrical: { operatingVoltageMin: 0, operatingVoltageMax: 0, logicVoltage: 0 },
      interfaces: [],
      protocols: []
    },
    aliases: ['power', 'power supply', 'psu', '12v'],
    keywords: ['psu', 'power', 'supply', '12v'],
    description: '12V DC Power Supply',
    visual: {
      symbol: 'power_supply',
      width: 140,
      height: 90,
    },
    geometry: {
      body: 'rect',
      pins: [
        { id: 'V+', x: 140, y: 30 },
        { id: 'V-', x: 140, y: 60 },
      ],
      boundingBox: { x: 0, y: 0, width: 140, height: 90 },
    },
    electrical: {
      pins: [
        {
          id: 'V+',
          name: 'V+',
          aliases: ['positive'],
          electricalType: 'power',
          direction: 'power_output',
          voltageDomain: '12V',
        },
        {
          id: 'V-',
          name: 'V-',
          aliases: ['negative'],
          electricalType: 'power',
          direction: 'power_input',
        },
      ],
    },
    knowledge: {
      notes: ['Regulated 12V output'],
      warnings: ['Short circuit protection is built-in'],
      applications: ['System power supply'],
      tags: ['power', 'supply', '12v'],
    },
  },
  // 10. Output: Lamp
  {
    id: 'Lamp',
    name: '12V Filament Lamp',
    tvcs: {
      categoryPath: ['Output'],
      manufacturer: 'Generic',
      series: '',
      family: 'Output',
      variant: '',
      tags: [],
      package: 'Generic',
      footprint: 'Generic',
      physicalDimensions: { widthMm: 0, lengthMm: 0, heightMm: 0 },
      electrical: { operatingVoltageMin: 0, operatingVoltageMax: 0, logicVoltage: 0 },
      interfaces: [],
      protocols: []
    },
    aliases: ['lamp', 'light'],
    keywords: ['lamp', 'light', 'bulb'],
    description: '12V Filament Lamp',
    visual: {
      symbol: 'lamp',
      width: 80,
      height: 80,
    },
    geometry: {
      body: 'circle',
      pins: [
        { id: '+', x: 0, y: 40 },
        { id: '-', x: 80, y: 40 },
      ],
      boundingBox: { x: 0, y: 0, width: 80, height: 80 },
    },
    electrical: {
      pins: [
        {
          id: '+',
          name: '+',
          aliases: ['positive'],
          electricalType: 'passive',
          direction: 'passive',
        },
        {
          id: '-',
          name: '-',
          aliases: ['negative'],
          electricalType: 'passive',
          direction: 'passive',
        },
      ],
    },
    knowledge: {
      notes: ['Filament bulb'],
      warnings: ['Will get hot during operation'],
      applications: ['Visual indicator', 'Load resistor'],
      tags: ['output', 'lamp'],
    },
  },
  {
    id: 'ArduinoUno',
    name: 'Arduino Uno',
    tvcs: {
      categoryPath: ['Physical'],
      manufacturer: 'Generic',
      series: '',
      family: 'Physical',
      variant: '',
      tags: [],
      package: 'Generic',
      footprint: 'Generic',
      physicalDimensions: { widthMm: 0, lengthMm: 0, heightMm: 0 },
      electrical: { operatingVoltageMin: 0, operatingVoltageMax: 0, logicVoltage: 0 },
      interfaces: [],
      protocols: []
    },
    aliases: ['uno_physical'],
    keywords: ['arduino', 'uno', 'microcontroller', 'mcu'],
    description: 'Arduino Uno R3',
    visual: { symbol: 'module', width: 686, height: 534 },
    geometry: { body: 'rect', pins: [], boundingBox: { x: 0, y: 0, width: 686, height: 534 } },
    electrical: { pins: [] },
    knowledge: { notes: [], warnings: [], applications: [], tags: ['mcu'] }
  },
  {
    id: 'ArduinoNano',
    name: 'Arduino Nano',
    tvcs: {
      categoryPath: ['Physical'],
      manufacturer: 'Generic',
      series: '',
      family: 'Physical',
      variant: '',
      tags: [],
      package: 'Generic',
      footprint: 'Generic',
      physicalDimensions: { widthMm: 0, lengthMm: 0, heightMm: 0 },
      electrical: { operatingVoltageMin: 0, operatingVoltageMax: 0, logicVoltage: 0 },
      interfaces: [],
      protocols: []
    },
    aliases: ['nano_physical'],
    keywords: ['arduino', 'nano', 'microcontroller', 'mcu'],
    description: 'Arduino Nano V3',
    visual: { symbol: 'module', width: 430, height: 180 },
    geometry: { body: 'rect', pins: [], boundingBox: { x: 0, y: 0, width: 430, height: 180 } },
    electrical: { pins: [] },
    knowledge: { notes: [], warnings: [], applications: [], tags: ['mcu'] }
  },
  {
    id: 'ESP32DevKit',
    name: 'ESP32 DevKit',
    tvcs: {
      categoryPath: ['Physical'],
      manufacturer: 'Generic',
      series: '',
      family: 'Physical',
      variant: '',
      tags: [],
      package: 'Generic',
      footprint: 'Generic',
      physicalDimensions: { widthMm: 0, lengthMm: 0, heightMm: 0 },
      electrical: { operatingVoltageMin: 0, operatingVoltageMax: 0, logicVoltage: 0 },
      interfaces: [],
      protocols: []
    },
    aliases: ['esp32_physical'],
    keywords: ['esp32', 'wifi', 'bluetooth', 'mcu'],
    description: 'ESP32 Development Board',
    visual: { symbol: 'module', width: 520, height: 280 },
    geometry: { body: 'rect', pins: [], boundingBox: { x: 0, y: 0, width: 520, height: 280 } },
    electrical: { pins: [] },
    knowledge: { notes: [], warnings: [], applications: [], tags: ['mcu', 'iot'] }
  },
  {
    id: 'ESP8266NodeMCU',
    name: 'ESP8266 NodeMCU',
    tvcs: {
      categoryPath: ['Physical'],
      manufacturer: 'Generic',
      series: '',
      family: 'Physical',
      variant: '',
      tags: [],
      package: 'Generic',
      footprint: 'Generic',
      physicalDimensions: { widthMm: 0, lengthMm: 0, heightMm: 0 },
      electrical: { operatingVoltageMin: 0, operatingVoltageMax: 0, logicVoltage: 0 },
      interfaces: [],
      protocols: []
    },
    aliases: ['nodemcu_physical'],
    keywords: ['esp8266', 'wifi', 'mcu'],
    description: 'ESP8266 NodeMCU Board',
    visual: { symbol: 'module', width: 480, height: 250 },
    geometry: { body: 'rect', pins: [], boundingBox: { x: 0, y: 0, width: 480, height: 250 } },
    electrical: { pins: [] },
    knowledge: { notes: [], warnings: [], applications: [], tags: ['mcu', 'iot'] }
  },
  {
    id: 'RaspberryPiPico',
    name: 'Raspberry Pi Pico',
    tvcs: {
      categoryPath: ['Physical'],
      manufacturer: 'Generic',
      series: '',
      family: 'Physical',
      variant: '',
      tags: [],
      package: 'Generic',
      footprint: 'Generic',
      physicalDimensions: { widthMm: 0, lengthMm: 0, heightMm: 0 },
      electrical: { operatingVoltageMin: 0, operatingVoltageMax: 0, logicVoltage: 0 },
      interfaces: [],
      protocols: []
    },
    aliases: ['pico_physical'],
    keywords: ['raspberry', 'pico', 'rp2040', 'mcu'],
    description: 'Raspberry Pi Pico RP2040',
    visual: { symbol: 'module', width: 510, height: 210 },
    geometry: { body: 'rect', pins: [], boundingBox: { x: 0, y: 0, width: 510, height: 210 } },
    electrical: { pins: [] },
    knowledge: { notes: [], warnings: [], applications: [], tags: ['mcu'] }
  },
  {
    id: 'LM2596Buck',
    name: 'LM2596 Buck Converter',
    tvcs: {
      categoryPath: ['Physical'],
      manufacturer: 'Generic',
      series: '',
      family: 'Physical',
      variant: '',
      tags: [],
      package: 'Generic',
      footprint: 'Generic',
      physicalDimensions: { widthMm: 0, lengthMm: 0, heightMm: 0 },
      electrical: { operatingVoltageMin: 0, operatingVoltageMax: 0, logicVoltage: 0 },
      interfaces: [],
      protocols: []
    },
    aliases: ['buck_physical', 'stepdown_physical'],
    keywords: ['power', 'step down', 'converter', 'lm2596'],
    description: 'DC-DC Step Down Converter Module',
    visual: { symbol: 'module', width: 430, height: 210 },
    geometry: { body: 'rect', pins: [], boundingBox: { x: 0, y: 0, width: 430, height: 210 } },
    electrical: { pins: [] },
    knowledge: { notes: [], warnings: [], applications: [], tags: ['power'] }
  },
  {
    id: 'OLED096',
    name: 'OLED 0.96"',
    tvcs: {
      categoryPath: ['Physical'],
      manufacturer: 'Generic',
      series: '',
      family: 'Physical',
      variant: '',
      tags: [],
      package: 'Generic',
      footprint: 'Generic',
      physicalDimensions: { widthMm: 0, lengthMm: 0, heightMm: 0 },
      electrical: { operatingVoltageMin: 0, operatingVoltageMax: 0, logicVoltage: 0 },
      interfaces: [],
      protocols: []
    },
    aliases: ['oled_physical', 'display_physical'],
    keywords: ['oled', 'display', 'i2c', 'screen'],
    description: '0.96 inch I2C OLED Display',
    visual: { symbol: 'module', width: 270, height: 270 },
    geometry: { body: 'rect', pins: [], boundingBox: { x: 0, y: 0, width: 270, height: 270 } },
    electrical: { pins: [] },
    knowledge: { notes: [], warnings: [], applications: [], tags: ['display'] }
  },
  {
    id: 'PushButton',
    name: 'Push Button',
    tvcs: {
      categoryPath: ['Physical'],
      manufacturer: 'Generic',
      series: '',
      family: 'Physical',
      variant: '',
      tags: [],
      package: 'Generic',
      footprint: 'Generic',
      physicalDimensions: { widthMm: 0, lengthMm: 0, heightMm: 0 },
      electrical: { operatingVoltageMin: 0, operatingVoltageMax: 0, logicVoltage: 0 },
      interfaces: [],
      protocols: []
    },
    aliases: ['button_physical', 'switch_physical'],
    keywords: ['input', 'button', 'tactile'],
    description: 'Tactile Push Button Switch',
    visual: { symbol: 'module', width: 120, height: 120 },
    geometry: { body: 'rect', pins: [], boundingBox: { x: 0, y: 0, width: 120, height: 120 } },
    electrical: { pins: [] },
    knowledge: { notes: [], warnings: [], applications: [], tags: ['input'] }
  },
  {
    id: 'RelayModule',
    name: 'Relay Module',
    tvcs: {
      categoryPath: ['Physical'],
      manufacturer: 'Generic',
      series: '',
      family: 'Physical',
      variant: '',
      tags: [],
      package: 'Generic',
      footprint: 'Generic',
      physicalDimensions: { widthMm: 0, lengthMm: 0, heightMm: 0 },
      electrical: { operatingVoltageMin: 0, operatingVoltageMax: 0, logicVoltage: 0 },
      interfaces: [],
      protocols: []
    },
    aliases: ['relay_physical'],
    keywords: ['output', 'relay', 'switch'],
    description: '1-Channel Relay Module',
    visual: { symbol: 'module', width: 430, height: 180 },
    geometry: { body: 'rect', pins: [], boundingBox: { x: 0, y: 0, width: 430, height: 180 } },
    electrical: { pins: [] },
    knowledge: { notes: [], warnings: [], applications: [], tags: ['output'] }
  }
];

export function loadInitialComponents(registry: ComponentRegistry): void {
  for (const comp of INITIAL_COMPONENTS) {
    registry.register(comp);
  }
}
